<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc2f6fde309cac5d55b9930359a6a3a6d
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'OSS\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OSS\\' => 
        array (
            0 => __DIR__ . '/..' . '/aliyuncs/oss-sdk-php/src/OSS',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc2f6fde309cac5d55b9930359a6a3a6d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc2f6fde309cac5d55b9930359a6a3a6d::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
